### ISSUE TITLE
Ability to access K8S dashboard from within Civo account

### ISSUE THREAD

**Issue by morganlaneap** [civo/kube100#1]
It would be great to be able to access the K8S dashboard from within Civo. In AKS, you can run `az aks browse`, so something similar I think would be a great feature. Would make things a lot quicker I think. 

A proxy through Civo to ensure authentication is probably a good approach, but what do you guys think?

**Comment by andyjeffries** [comment]
Are you thinking specifically through the UI or through the CLI?

**Comment by morganlaneap** [comment]
@andyjeffries Could start with the CLI, with a similar command to AKS (only worked with AKS so far), but perhaps a UI functionality would be possible? Just thinking in terms of convenience...

**Comment by andyjeffries** [comment]
I'd need to adjust the firewall system to allow this (have plans to do it anyway), but would you be OK if it effectively just used normal Kubernetes forwarding to the dashboard from your current IP (and punched that through the firewall, removing the rule again later somehow)?

**Comment by andyjeffries** [comment]
So it would make the commands:

* Open firewall port for the current IP to access a dashboard port
* Launch the dashboard
* Kubectl proxy to it
* Wait for user to Ctrl-C
* Remove dashboard
* Remove firewall rule

**Comment by morganlaneap** [comment]
@andyjeffries I'm sure that would be a good start, I believe AKS browsing from the CLI does something similar. In the interest of security, there could be a timeout in case the user is inactive for a long period, but that could be a future consideration for this feature.

**Comment by morganlaneap** [comment]
@andyjeffries I've created a PR for this now. Finally got round to it! https://github.com/civo/kubernetes-marketplace/pull/45

**Comment by kaihoffman** [comment]
Fixed with pull request 45, thanks Morgan!
