### ISSUE TITLE
Unable to use longhorn in a 0.10.0 cluster

### ISSUE THREAD

**Issue by planetf1** [civo/kube100#11]
* Installed a 0.10.0 cluster (small & medium tried)
* Set default storage class to longhorn (and removed default annotation from local disk)
* Deployed an app (wordpress helm chart) that makes use of pvcs
* pv were allocated, however the pods using them cannot mount:
```
 Warning  FailedMount         5m10s (x4 over 14m)  kubelet, kube-node-99f8  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[data config default-token-2ntvn]: timed out waiting for the condition
  Warning  FailedAttachVolume  116s (x15 over 16m)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-a127ff75-0d2f-4a03-b4ad-7d89838478dc" : node "kube-node-99f8" has no NodeID annotation
  Warning  FailedMount         40s (x3 over 11m)    kubelet, kube-node-99f8  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[config default-token-2ntvn data]: timed out waiting for the condition
```
Created a number of clusters, but this error was repeated each time.

**Comment by planetf1** [comment]
Confirming this still occurs with version=development as of 15 Nov.

**Comment by planetf1** [comment]
Trying a direct install of longhorn... but longhorn frontend will fail with
```
  Warning  FailedScheduling  <unknown>  default-scheduler  0/3 nodes are available: 2 node(s) didn't match node selector, 3 node(s) didn't have free ports for the requested pod ports.
  Warning  FailedScheduling  <unknown>  default-scheduler  0/3 nodes are available: 2 node(s) didn't match node selector, 3 node(s) didn't have free ports for the requested pod ports.
```
(due to ingress / web no doubt)

**Comment by andyjeffries** [comment]
Could you raise this on Longhorn's bug tracker please. You can tag me @andyjeffries in it and I can provide any debug information they need directly from the underlying instances.

I'm at Kubecon next week so if Darren Shepherd (lead developer of k3s) needs access to the box, I can do it live with him.

Many thanks.

**Comment by planetf1** [comment]
Opened against longhorn - or rather I should say adding to an existing open issue which seems to hit the exact same error

**Comment by planetf1** [comment]
@andyjeffries the longhorn team have replied and indicate the issue is down to the kubelet path being different.

UJnfortunately I don't know what paths you use - so there's a combination here of
 - The civo application should set this correctly
 - may need a doc/tip on the site to explain how to specify manually
 - need to consider whether there is a more general impact
 - I'll let you assess if the debugging/errors/logic reported by longhorn are sufficient or should be improved

**Comment by andyjeffries** [comment]
Thanks @planetf1 I'm still in San Diego, having just finished Kubecon. So this only affects 0.10.0 and below? Above 0.10.0 it's OK? Am I reading that right (at 7:30am after a busy week in a different time zone) 😉

If so, we're unlikely to fix this as we're now switching the default version of k3s to be 1.0.0 as it's GA.

**Comment by planetf1** [comment]
Unfortunately it did seem to affect 1.0.0 for me as per https://github.com/longhorn/longhorn/issues/392
even though the initial issue is much older.

I can't really try any fix as it requires knowing the filesystem layout in the cluster and as ever worth verifying that I haven't done anything stupid in my attempt.

Kubecon :-)

**Comment by andyjeffries** [comment]
Just updating Longhorn to 0.7.0 which apparently fixes this. I'll update in Civo's Community Slack when it's deployed to production for testing.
