### ISSUE TITLE
Ability to select a firewall on cluster creation

### ISSUE THREAD

**Issue by Zurgy** [civo/kube100#15]
I'd appreciate the ability to select a pre-existing firewall configuration when creating a new cluster.

As a developer who wants to learn Kubernetes I deploy all kinds of random rubbish to my cluster and want a restrictive firewall that allows everything in from my home IP and blocks everything else.

I regularly break the cluster so delete it and create a new one but have to reconfigure the firewall every time. I could be less security conscious and leave the default open access firewall as the cluster is usually short-lived but prefer not to.

**Comment by daryll-swer** [comment]
The feature has been implemented. Closing.
