### ISSUE TITLE
User is able install MinIO on cluster without any plan selected

### ISSUE THREAD

**Issue by DanielCalvo** [civo/kube100#18]
To install Minio, I'm required to select a plan. But when I select a plan, I can go back to "Choose your plan" with the window selected and install it without a plan selected.

![ezgif-3-4442a2ec417b](https://user-images.githubusercontent.com/859049/75916836-52a70800-5e59-11ea-88f1-7678f8efe0d8.gif)

Also I'm not a UI expert but from an usability standpoint -- wouldn't it be more intuitive if the window was selected as soon as I select a plan? Currently I have to click again.

**Comment by daryll-swer** [comment]
Issue has been fixed.
