### ISSUE TITLE
Node status in dashboard incorrect.

### ISSUE THREAD

**Issue by danielgelling** [civo/kube100#20]
When looking in the Civo kubernetes dashboard it looks like all nodes are running and healthy. However querying the node statuses via `kubectl get nodes` it tells us something different.

<img width="669" alt="Screenshot 2020-03-29 at 16 25 30" src="https://user-images.githubusercontent.com/6146135/77851713-d9da6800-71da-11ea-820a-7e3a8196741a.png">

**Comment by andyjeffries** [comment]
The status in the Civo dashboard is currently the status of the underlying instance (e.g. it's running), that k3s considers it to be NotReady (but knows it exists therefore is running) is a different problem. There was an issue sometimes with k3s not marking the nodes as ready. The latest release seems to fix that, but with their new choice of version naming they've broken our site so we aren't ready to use it (`v1.17.3+k3s1` - the `+` breaks semantic version parsing).

Still we aim to get to a point where we're closer integrated with the clusters, so I'll leave this issue open.

**Comment by daryll-swer** [comment]
Issue has been solved.
