### ISSUE TITLE
Silent failure of Marketplace when Helm upgraded

### ISSUE THREAD

**Issue by cablespaghetti** [civo/kube100#21]
Hi,

I upgraded Helm Tiller on my cluster to 2.16 to match with the Helm client I had installed on my laptop. 2.14 is installed by default (see https://github.com/civo/kubernetes-marketplace/issues/39). 

Unfortunately this seems to have broken the marketplace and installs just fail silently now. At the very least an error message in the web UI would be a good improvement in this case.

Thanks

**Comment by daryll-swer** [comment]
Helm has been upgraded to v3. The issue wasn't reproducible in v3.
