### ISSUE TITLE
Waiting at least 45 minutes for cluster to create, didn't finish

### ISSUE THREAD

**Issue by amitkgupta** [civo/kube100#23]
I ran:

```
civo k8s create --wait --save --version=0.9.1
```

In the terminal, it was stuck with the spinner spinning for at least 45 minutes. Logging into the GUI, the progress bar was mostly at the end, and said something like "almost done, finalizing your cluster" for probably the last 20-30 minutes of that 45 minutes. Seemed like it was never going to succeed, eventually gave up and deleted the requested cluster. Previous clusters I have created without specifying a `--version` (and just using the default) finished creating in under 5 minutes.

**Comment by andyjeffries** [comment]
We wouldn't recommend using an old version. We leave that in the version list so it doesn't break anyone with old cluster versions still running.
