### ISSUE TITLE
Terraform: Attempting to create a Kubernetes cluster without a provider crashes Terraform

### ISSUE THREAD

**Issue by theothertomelliott** [civo/kube100#28]
**Reproduction steps:**

Create a new directory with the following `main.tf`:
```
resource "civo_kubernetes_cluster" "cluster1" {
    name = "test-cluster"
    num_target_nodes = 2
}
```

Run the following inside the new dir:
```
terraform init
terraform apply
```

The terraform output will indicate a crash.

**Environment:**
Terraform v0.12.26
civo plugin 0.9.4
macOS v10.15.4

**Comment by sr229** [comment]
I was able to replicate this as well with the versions provided. Might be the Civo plugin at fault?

**Comment by alejandrojnm** [comment]
I will check this, thx for all

**Comment by alejandrojnm** [comment]
Hi, @theothertomelliott In this version [v0.9.5](https://github.com/civo/terraform-provider-civo/releases/tag/v0.9.5) it should no longer crash terraform, if the provider is not found, It will only show an error

**Comment by theothertomelliott** [comment]
Works great, I'm now getting a "token not found" error. Thanks for the quick turnaround!

**Comment by alejandrojnm** [comment]
Np, next time open the issue in the terraform provider repo
