### ISSUE TITLE
Civo dashboard scaling issue

### ISSUE THREAD

**Issue by will2therich** [civo/kube100#3]
I have noticed what seems to be a small UI issue with scaling.
If you scale to the same number of nodes you already have it will always say " This cluster is scaling." on first page load.

How to reproduce:
Create a Kubernetes Cluster.
Resize the cluster but dont actually change the ammount of nodes.

Now in the kubernetes cluster list and each cluster's page. It will eventually update to " This cluster is running. " but It can be confusing.

Maybe best not letting you hit rescale unless you have actually changed the ammount of nodes in the cluster?

**Comment by andyjeffries** [comment]
Thanks for reporting this. We'll now ignore if you try to scale to the same number of nodes that you're currently using.
