### ISSUE TITLE
Provide view permissions to the instances

### ISSUE THREAD

**Issue by soukron** [civo/kube100#31]
Having access to the instances using the web console (the IaaS tab) would provide statistics about the usage of them. That's good information to know if a cluster upgrade is required or a smaller kind of instances will be enough or not.

**Comment by andyjeffries** [comment]
Our frontend guy is working to integrate the same usage reporting that's on the instances view to the cluster view. We wouldn't want the underlying instances on the IaaS Instances view though, that kind of ties us to keeping them there and in future they may not be using underlying instances (k3v for example).
