### ISSUE TITLE
can't add firewall rules

### ISSUE THREAD

**Issue by camaeel** [civo/kube100#34]
I've created new kubernetes and now I'm trying to add some rules, but adding new rules doesn't work.

**Comment by AugustasV** [comment]
@camaeel Could you share steps you took to create new rules, and what output you got? Screenshots would be use too.

**Comment by camaeel** [comment]
The original path was:
1. create a new cluster, wait for it to be completed. 
2. Go to firwall tab
3. Click book icon next to my Kubernetes clusters firewall
4. Fill something like: Port from 80, port to 80, CIDR: 0.0.0.0/0 (or anything else)
5. Nothing happens.

Browser Opera @Linux mint. 

At the moment civo has no free resources to create a new Kubernetes cluster so I can't provide any screenshots. 

Similar symptoms I get when I just try to create a new firewall. Steps to reproduce:
1. go to firwall tab
2. CLick "+ Create firewall"
Browser CHrome@Win10 or Opera@Win10. 

In browser console I get:
```
VM103:8 Uncaught SyntaxError: Invalid or unexpected token
    at eval (<anonymous>)
    at Function.globalEval (application-5a96a827a6baac8691113b27afbd22b33a276a669b99c35b57ec5b67926b2272.js:14)
    at x (application-5a96a827a6baac8691113b27afbd22b33a276a669b99c35b57ec5b67926b2272.js:14)
    at ot.fn.init.append (application-5a96a827a6baac8691113b27afbd22b33a276a669b99c35b57ec5b67926b2272.js:26)
    at b.appendContent (application-5a96a827a6baac8691113b27afbd22b33a276a669b99c35b57ec5b67926b2272.js:555)
    at Object.success (application-5a96a827a6baac8691113b27afbd22b33a276a669b99c35b57ec5b67926b2272.js:555)
    at u (application-5a96a827a6baac8691113b27afbd22b33a276a669b99c35b57ec5b67926b2272.js:25)
    at Object.fireWith [as resolveWith] (application-5a96a827a6baac8691113b27afbd22b33a276a669b99c35b57ec5b67926b2272.js:25)
    at i (application-5a96a827a6baac8691113b27afbd22b33a276a669b99c35b57ec5b67926b2272.js:26)
    at XMLHttpRequest.<anonymous> (application-5a96a827a6baac8691113b27afbd22b33a276a669b99c35b57ec5b67926b2272.js:26)
globalEval @ application-5a96a827a6baac8691113b27afbd22b33a276a669b99c35b57ec5b67926b2272.js:14
x @ application-5a96a827a6baac8691113b27afbd22b33a276a669b99c35b57ec5b67926b2272.js:14
append @ application-5a96a827a6baac8691113b27afbd22b33a276a669b99c35b57ec5b67926b2272.js:26
appendContent @ application-5a96a827a6baac8691113b27afbd22b33a276a669b99c35b57ec5b67926b2272.js:555
success @ application-5a96a827a6baac8691113b27afbd22b33a276a669b99c35b57ec5b67926b2272.js:555
u @ application-5a96a827a6baac8691113b27afbd22b33a276a669b99c35b57ec5b67926b2272.js:25
fireWith @ application-5a96a827a6baac8691113b27afbd22b33a276a669b99c35b57ec5b67926b2272.js:25
i @ application-5a96a827a6baac8691113b27afbd22b33a276a669b99c35b57ec5b67926b2272.js:26
(anonymous) @ application-5a96a827a6baac8691113b27afbd22b33a276a669b99c35b57ec5b67926b2272.js:26
load (async)
send @ application-5a96a827a6baac8691113b27afbd22b33a276a669b99c35b57ec5b67926b2272.js:26
ajax @ application-5a96a827a6baac8691113b27afbd22b33a276a669b99c35b57ec5b67926b2272.js:26
getAjax @ application-5a96a827a6baac8691113b27afbd22b33a276a669b99c35b57ec5b67926b2272.js:555
updateItemHTML @ application-5a96a827a6baac8691113b27afbd22b33a276a669b99c35b57ec5b67926b2272.js:555
open @ application-5a96a827a6baac8691113b27afbd22b33a276a669b99c35b57ec5b67926b2272.js:555
_openClick @ application-5a96a827a6baac8691113b27afbd22b33a276a669b99c35b57ec5b67926b2272.js:555
i @ application-5a96a827a6baac8691113b27afbd22b33a276a669b99c35b57ec5b67926b2272.js:555
dispatch @ application-5a96a827a6baac8691113b27afbd22b33a276a669b99c35b57ec5b67926b2272.js:26
g.handle @ application-5a96a827a6baac8691113b27afbd22b33a276a669b99c35b57ec5b67926b2272.js:25```

**Comment by AugustasV** [comment]
Firewall is  portion of civo services, which includes volumes, VPS instances, and others. You will have to add in a payment  method to be able to change those. Currently the firewall that gets auto-configured for your k3s clusters is set up to allow you to do anything you will need on the cluster without changes being required.

**Comment by TibebeJS** [comment]
> Firewall is portion of civo services, which includes volumes, VPS instances, and others. You will have to add in a payment method to be able to change those. Currently the firewall that gets auto-configured for your k3s clusters is set up to allow you to do anything you will need on the cluster without changes being required.

Oh okay, thanks for the insight. But it would be awesome to point that out on the firewall page as some sort of alert (because you can actually delete these rules there, and not get them back afterwards)
Also, the page doesn't actually handle the issue gracefully (no popups, alerts, etc..) - it simply throws error.
![bug](https://user-images.githubusercontent.com/45547122/92517516-76d80d00-f21f-11ea-97cf-e94e04b1aab8.png)

**Comment by crochik** [comment]
A workaround I found till the new firewall (or a fix) is available is to use the api to add firewall rules. It is quite easy and worked without issues.  The civo cli should probably also work.

**Comment by darrenallen85** [comment]
using the CLI to add a firewall works fine.

eg to add a firewall rule to allow access from my source ip only : 

civo firewall rule create civo2 -c 104.164.64.101/32 -d ingress -e 27017 -l mongodb -p TCP -s 27017

**Comment by kaihoffman** [comment]
This was fixed in a previous iteration to our codebase but has now been re-implemented. You should be able to create/edit firewall rules on the web control panel for your clusters.
