### ISSUE TITLE
Version reported in GUI

### ISSUE THREAD

**Issue by camaeel** [civo/kube100#35]
New clsuter shows version: k3s v1.0.0
But when I run kubectl version, I get:
`Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3-k3s.2", GitCommit:"e7e6a3c4e9a7d80b87793612730d10a863a25980", GitTreeState:"clean", BuildDate:"2019-11-18T18:31:23Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}`

It would be better to show real k3s versions. Current version is at least confusing

**Comment by andyjeffries** [comment]
That is the "real k3s version", https://github.com/rancher/k3s/releases/tag/v1.0.0

We are planning on making a much newer version of k3s available soon, but as they changed the versioning format, this has broken our code so we have changes to do rather just update our mirror and put the new version string in.

**Comment by camaeel** [comment]
You are right. Thank you.
