### ISSUE TITLE
on the WebUI set a version for k3s is missing on creation or upgrade

### ISSUE THREAD

**Issue by curx** [civo/kube100#39]
In the [civo/cli](https://github.com/civo/cli) there is the possibility to set the k3s version during the installation or to perform an upgrade 
unfortunately, the possibility is missing in the WebUI

**Comment by andyjeffries** [comment]
We're envisaging only having a single "production" version available at any time (plus legacy/non-selectable ones for people who haven't yet upgraded). At the CLI we give the option of testing out development releases ahead of times, but intentionally don't have that in the Web UI as CLI users are generally more power-users so are more likely to be accepting of the "here be dragons" style of using a non-stable release.

**Comment by curx** [comment]
Thanks for clarifying, make sense.
