### ISSUE TITLE
Firewall: are all ports open or closed?

### ISSUE THREAD

**Issue by crochik** [civo/kube100#49]
I found several other posts about not being able to [add firewall rules w/o a creditcard](https://github.com/civo/kube100/issues/34) (it actually works using the API). What I don't understand is that by default the firewall rules allow access to all ports but one. At the same time the message on the firewall page say exactly the opposite:

```
All ports are closed for custom firewalls by default. You'll need to specifically open the ports you require.
```

I changed all the rules to only allow traffic from my IP and with that probably blocked the nodes from talking to each other. Is there a pre-defined private subnet that I can use to allow my nodes to talk to each other but block external IPs? As now it seems that it is all or nothing. .. And even just for testing I would be worried about having all ports open

**Comment by andyjeffries** [comment]
The documentation for firewalls refers more to IAAS things and could do with a brush up, but @Kai Hoffman was building a funky new firewall configuration for k3s clusters that hasn't launched yet. The default for k3s clusters is all ports are open, EXCEPT for the virtual networking port used for private networking between the instances.

**Comment by crochik** [comment]
@andyjeffries is @kaihoffman 's "funky new firewall configuration" coming soon? Currently, is there any way to limit the ports in the master node available to the "world"?
