### ISSUE TITLE
Display DNS Name in Civo CLI

### ISSUE THREAD

**Issue by pslobo** [civo/kube100#5]
I'd like to request that `civo k3s show <cluster-name>` also display the DNS Name assigned to the cluser. Granted, the we could simply append `k8s.civo.com` to the cluster ID, but it would be easier to have the DNS name there already (took me a short while to associate the DNS Name with the Cluster ID).

**Comment by andyjeffries** [comment]
This was done in v0.4.4 earlier today.

**Comment by andyjeffries** [comment]
Thanks for the issue :-)
