### ISSUE TITLE
The date time on nodes may be incorrect

### ISSUE THREAD

**Issue by wi1dcard** [civo/kube100#52]
Hi team,

There are about 30 seconds lag on some of my nodes. I started a privileged container and enter the node shell, found that the ntp service is not installed on the node.

This might not be an urgent issue, but I'm using the beta version, so I think it is better to report this one instead of being silent.

**Comment by andyjeffries** [comment]
Thanks for this. I've added it to the build for new clusters. Should be live on the site sometime today. I definitely appreciate the report.

**Comment by wi1dcard** [comment]
Thanks @andyjeffries ! Is it required to relaunch all nodes in order to get the latest build?

**Comment by andyjeffries** [comment]
You'd have to launch a new cluster in reality. However, if you need it done for an existing cluster, reach out on our community Slack and I can try to do it on your master for you, then you can recycle each node to get those built fresh.

**Comment by kaihoffman** [comment]
Would this be OK to close, @wi1dcard ?

**Comment by wi1dcard** [comment]
> Would this be OK to close, @wi1dcard ?

Sure yes! I recreated the cluster a week ago, the time of nodes has not lagged behind.
