### ISSUE TITLE
Cloud Shell For Civo

### ISSUE THREAD

**Issue by ssmiller25** [civo/kube100#54]
Provide a web-based terminal in the main web administration interface, to allow for configuration and cli access to Civo and it's Kuberntes clusters.  I envision something similar to [Azure's CloudShell](https://github.com/Azure/CloudShell) (MIT licensed) or Google's similar cloud-shell.  This would provide a method to completely configure a Kube100 cluster from the web interface, including any post-install configuration of apps.  This could also partially address #40 (although really, a dedicated web-based YAML applicator would still be nice, apart from a Cloud Shell)

I would be eager to help with this effort.

**Comment by andyjeffries** [comment]
Could you raise this at https://www.civo.com/account/suggestions please @ssmiller25 . We tend to use that for proposed features so we can let customers vote on them (and then schedule them to our roadmap). Saiyam is releasing a blog post on our roadmap soon... Thanks.
