### ISSUE TITLE
Create node pool UI elements do not reflect quota limits

### ISSUE THREAD

**Issue by chrisk700** [civo/kube100#71]
When creating a new cluster certain elements may be unavailable based on your quota. When creating a new node pool these are not reflected and you can choose any options which may result in an error page being displayed (the backend honours the quota).

Cluster creation:
![image](https://user-images.githubusercontent.com/74745915/117029776-e642c580-acf6-11eb-91fb-4a5062789286.png)

Node Pool creation:
![image](https://user-images.githubusercontent.com/74745915/117029822-f22e8780-acf6-11eb-9dad-280db4b3f428.png)

**Comment by tahsin352** [comment]
@chrisk700 fixed it.
