### ISSUE TITLE
API documentation page for kubernetes does not switch on tab change

### ISSUE THREAD

**Issue by akosveres** [civo/kube100#80]
Navigating to https://www.civo.com/api/kubernetes and going to the bottom of the page, if I click on `Nodejs` or `Ruby`, the code for `Example of listing versions` does not show.

No errors in console log and works for other tabs on the page.

Running on Firefox 88.0 on MacOS v10.15.6.

**Comment by andyjeffries** [comment]
Thanks for reporting this, it's fixed now.
