### ISSUE TITLE
GitLab integration: AttachVolume.Attach failed for volume

### ISSUE THREAD

**Issue by k33g** [civo/kube100#81]
Hello,

First, I created a Civo cluster (I tried with the large one and the extra-large one) with default applications

Then I started to setup the GitLab Kube integration with a group on GitLab.com following this: https://docs.gitlab.com/ee/user/project/clusters/add_remove_clusters.html#add-existing-cluster

The "link" with the cluster was ok

Then, I added the GitLab Kubernetes executor (from the GitLab UI), and it worked like a charm, I was able to run my GitLab CI pipeline
Then, I wanted to install the Prometheus application from the GitLab UI and I never finished the deployment (I'm not a kube specialist, but I think I have a problem with the pvc claim)

From K9S, I did a "describe" on the installation pod:

```
│ Events:                                                                                                                                │
│   Type     Reason              Age                 From                     Message                                                    │
│   ----     ------              ----                ----                     -------                                                    │
│   Warning  FailedScheduling    <unknown>                                    0/1 nodes are available: 1 pod has unbound immediate Persi │
│ stentVolumeClaims.                                                                                                                     │
│   Warning  FailedScheduling    <unknown>                                    0/1 nodes are available: 1 pod has unbound immediate Persi │
│ stentVolumeClaims.                                                                                                                     │
│   Normal   Scheduled           <unknown>                                    Successfully assigned gitlab-managed-apps/prometheus-prome │
│ theus-server-5f67877494-cqhj7 to k3s-chewie-cb3a47bd-node-pool-7e39                                                                    │
│   Warning  FailedAttachVolume  36s (x8 over 100s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-63e23ea1-4965-4 │
│ d9d-b9a5-65458aef59e4" : rpc error: code = DeadlineExceeded desc = context deadline exceeded 
```

I did a local setup (1 GitLab VM + 1 K3S VM) and I was able to setup the integration with Prometheus

**Comment by andyjeffries** [comment]
We believe there are volume issues on LON1 at the moment. We're working on them. NYC1 appears to be fine.

**Comment by andyjeffries** [comment]
We'll be updating progress at https://status.civo.com/issues/2021-05-12-cluster-launches-temporarily-disrupted/ for this issue, but the team is hard at work on it.

**Comment by k33g** [comment]
@andyjeffries thank you for your answer 😃 good luck
