### ISSUE TITLE
Cluster created & running, but it's not visible in the Kubernetes page of civo.com

### ISSUE THREAD

**Issue by eleaese** [civo/kube100#85]
I created a cluster at my account (luis@impulseit.com), cluster name tea-cluster-1. The cluster spinned up, and it was visible in the Kubernetes option on the left menu. I was able to download the KUBECONFIG file, and could manage the cluser from kubectl.

I entered today at https://www.civo.com/account/kubernetes, and the cluster is not there, see civo-dashboard-1.png & civo-dashboard-2.png. However the cluster is running,as you could see in k9s-panel.png.

Please take a look to fix it, thank you.

<img width="1649" alt="civo-dashboard-1" src="https://user-images.githubusercontent.com/1958568/124029131-ce1fb780-d9c2-11eb-8e0f-665e66d2a44a.png">
<img width="1649" alt="civo-dashboard-2" src="https://user-images.githubusercontent.com/1958568/124029129-cd872100-d9c2-11eb-8c31-c7ee35399940.png">
<img width="1650" alt="k9s-panel" src="https://user-images.githubusercontent.com/1958568/124029105-c8c26d00-d9c2-11eb-9d1d-2078b249d483.png">

**Comment by andyjeffries** [comment]
Wow, so sorry, apparently I didn't notice this issue. Are you still able to access it now? If so, what's the IP of the cluster please. I can't see it when logged in to your account either.

**Comment by eleaese** [comment]
Hi Andy, it was my fault, I was looking for the cluster in another region.
It's a bug on my side :-)

Regards

Luis

**Comment by andyjeffries** [comment]
Ahh OK, cool. No worries. Have a great weekend.
