### ISSUE TITLE
Actual Public IP Addresses In k3s

### ISSUE THREAD

**Issue by ssmiller25** [civo/kube100#9]
It would be helpful if actual external addresses were represented within civo k3s clusters.  The two examples I can specifically call out:

* If the actual "ExternalIP" was set appropriately on node objects (say, a `kubectl describe node` would provide the ExternalIP along with the InternalIP)
* On Loadbalancer service objects, the "External-IP" actually represented the external address(es) available to the cluster.

I can get that information through the civo CLI/API, but it would be handy if that info was accurately expressed natively.   This would make transition from other managed kubernetes services a bit easier.

**Comment by andyjeffries** [comment]
We're planning on removing the public IP addresses on the worker nodes anyway (this was discussed within #kube100 on our community slack), so going forward there will only be a single IP for the cluster. This fits our use case of "dev/test/learning" clusters rather than production. There's no current Loadbalancer integration, so I'm not sure what IP that's actually using.

**Comment by ssmiller25** [comment]
Ok, makes sense that you are targeting dev/test/learning environment, and not production, so ExternalIPs aren't as necessary.

I would like to propose that providing the actual external IP for svc objects would aid development.  Currently to get the external address I need to use the civo cli, the web interface, or use `kubectl cluster-info` to get the master node's address.  I'd love to see the external IP reported by `kubectl get svc -n kube-system traefik` actually show the real IP addresses of the cluster.  It kind of looks like `LoadBalanced` type services are exposed using k3s's [servicelb](https://github.com/rancher/k3s/tree/master/pkg/servicelb).  But I can also see how this might be a modest development effort to provide information that really can be gathered through other means.

**Comment by andyjeffries** [comment]
Just tried to fix the real IP of the cluster. It feels like a bit of a kludge, you have to set the same external IP on all nodes (as we now only have a single public IP on the development version), but it seems to work:

```
$ civo k3s create --wait --version=development
Building new Kubernetes cluster craft-jessica: Done
Created Kubernetes cluster craft-jessica in 01 min 33 sec

$ civo k3s config craft-jessica > cj

$ KUBECONFIG=cj kubectl get svc traefik -n kube-system
NAME      TYPE           CLUSTER-IP        EXTERNAL-IP      PORT(S)                                     AGE
traefik   LoadBalancer   192.168.223.118   91.211.152.186   80:30206/TCP,443:31520/TCP,8080:30640/TCP   13m
```

Feel free to give it a go for yourself if you launch a development cluster from the CLI.

**Comment by ssmiller25** [comment]
That works great!  My primary use case is to use external-dns, and this allows that service to function properly.  Thanks!

**Comment by andyjeffries** [comment]
This seems to have regressed with 1.0.0, reopening...

**Comment by andyjeffries** [comment]
And it's back fixed again :-)
