### ISSUE TITLE
Current account Text Overflow from sidebar

### ISSUE THREAD

**Issue by Manty-K** [civo/kube100#92]
If our email is big it overflows from the Civo Sidebar

**Comment by daryll-swer** [comment]
Hi

This repo is no longer being maintained or monitored, you can reach out to Civo support directly via [civo.com](https://civo.com/) itself or via our Community Slack for help and bug reports (if any), or you could create an issue on the [respective repos (if any)](https://github.com/orgs/civo/repositories)
